# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files

# Static analysis and formatting for Python code with ruff
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
    # Run the linter
    -   id: ruff-check
        args: ['--fix']
    # Run the formatter
    -   id: ruff-format

# Finds unused Python code
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.12
    hooks:
    -   id: vulture
        exclude: ^rednotebook/external/
