#! /usr/bin/env bash
#
# Little helper script that runs RedNotebook without installing it.
#
# Note: No need to translate strings locally, since they won't be
# picked up anyway.
#

set -euo pipefail

# Change into RedNotebook directory.
cd "$(dirname "$0")"

# Run RedNotebook.
python3 rednotebook/journal.py "$@"
