#! /bin/bash
#
# Little helper script that runs RedNotebook without installing it.
#

set -euo pipefail

# Change into RedNotebook directory

BASEDIR="$(dirname "$0")"
cd $BASEDIR

# Run RedNotebook

python2.7 rednotebook/journal.py "$@"
