#!/usr/bin/env python

# Allow running this script in source directory
try:
	# Load module from same directory
	import redNotebook
	redNotebook.main()
except ImportError:
	# Load installed module
	import rednotebook.redNotebook
	rednotebook.redNotebook.main()
