#!/usr/bin/env python

# Dirty fix for Python 2.6 compatibility, will be fixed properly soon
import sys
sys.path.insert(0, '/usr/lib/python2.5/site-packages')

import rednotebook.redNotebook
rednotebook.redNotebook.main()
