name: Ubuntu

# see https://github.community/t5/GitHub-Actions/How-to-trigger-an-action-on-push-or-pull-request-but-not-both/m-p/35805
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Show environment
      run: |
        python --version
        python3 --version
        python3 -c "import multiprocessing as m; print('CPUs:', m.cpu_count())"

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install -qq gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-gtk-3.0 gir1.2-pango-1.0 gir1.2-webkit2-4.0 python3 python3-enchant python3-gi python3-yaml tox

    - name: Check style
      run: |
        tox -e style

    - name: Run tests
      run: |
        tox -e py
